# Generated by Django 4.2.2 on 2023-06-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resort_app", "0004_coal_jsjs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation_Coal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=200)),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                ("number_of_guests", models.IntegerField()),
                ("room_type", models.CharField(max_length=100)),
                ("mode_of_payment", models.CharField(max_length=100)),
                ("total_amount", models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation_JSJS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=200)),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                ("number_of_guests", models.IntegerField()),
                ("room_type", models.CharField(max_length=100)),
                ("mode_of_payment", models.CharField(max_length=100)),
                ("total_amount", models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation_Terraces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=200)),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                ("number_of_guests", models.IntegerField()),
                ("room_type", models.CharField(max_length=100)),
                ("mode_of_payment", models.CharField(max_length=100)),
                ("total_amount", models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation_Viking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=200)),
                ("cottage_type", models.CharField(max_length=100)),
                ("mode_of_payment", models.CharField(max_length=100)),
                ("total_amount", models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
    ]
